[general]
import = [ "~/.config/alacritty/themes/themes/catppuccin.toml" ]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/home/oskar/.local/bin/tmux-launcher.sh"

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
size = 12.0

[terminal]
